### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by phyukhaing7** [ffmpbgrnn/pycocoevalcap#1]
When I use the pycocoevalcap for evaluate the accuracy of the captions, I face with the following error in my computer. But, when I test on the other computer, it is okay. How can I solve that problem in my computer?
Please help!

`D:\Anaconda3\envs\evaluationMetrics\python.exe D:/Research/code/Python/evaluationMetrics/demo_cocoeval.py
Traceback (most recent call last):

  File "D:/Research/code/Python/evaluationMetrics/demo_cocoeval.py", line 107, in <module>
    print(calculate_metrics(rng, datasetGTS, datasetRES))
  File "D:/Research/code/Python/evaluationMetrics/demo_cocoeval.py", line 89, in calculate_metrics

    evalObj.evaluate()
  File "D:/Research/code/Python/evaluationMetrics/demo_cocoeval.py", line 24, in evaluate
    gts = tokenizer.tokenize(gts)
  File "D:\Research\code\Python\evaluationMetrics\pycocoevalcap\tokenizer\ptbtokenizer.py", line 54, in tokenize
    p_tokenizer = subprocess.Popen(cmd, cwd=path_to_jar_dirname, stdout=subprocess.PIPE)
  File "D:\Anaconda3\envs\evaluationMetrics\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\envs\evaluationMetrics\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1
`

**Comment by abhineet99** [comment]
Installing java solved it for me.
